#ifndef FMO_EXPLORER_IMPL_HPP
#define FMO_EXPLORER_IMPL_HPP

#include <fmo/agglomerator.hpp>
#include <fmo/algorithm.hpp>
#include <fmo/subsampler.hpp>
#include <fmo/stats.hpp>
#include <fmo/strip.hpp>

namespace fmo {
    /// Implementation details of class Explorer.
    struct ExplorerV3 final : public Algorithm {
        virtual ~ExplorerV3() override;

        /// Initializes all caches. Creates as many decimation levels as needed to process images
        /// with specified dimensions. The following calls to setInputSwap() will require that the
        /// format and dimensions match the format and dimensions provided here.
        ExplorerV3(const Config& cfg, Format format, Dims dims);

        /// To be called every frame, providing the next image for processing. The processing will
        /// take place during the call and might take a long time. The input is received by swapping
        /// the contents of the provided input image with an internal buffer.
        virtual void setInputSwap(Image& input) override;

        /// To be called every frame, obtaining a list of fast-moving objects that have been
        /// detected this frame. The returned objects (i.e. instances of class Detection) may be
        /// used only before the next call to setInputSwap().
        virtual void getOutput(Output&) override;

        /// Provide the offset of the frame number in which the detected objects are being reported
        /// relative to the current input frame.
        virtual int getOutputOffset() const override { return -1; }

        /// Visualizes the result of detection, returning an image that is useful for debugging
        /// algorithm behavior. The returned image will have BGR format and the same dimensions as
        /// the input image.
        virtual const Image& getDebugImage() override {
            visualize();
            return mCache.visColor;
        }

    private:
        /// Strip generated by searching in a difference image.
        using ProtoStrip = Strip;

        /// Strip generated by merging ProtoStrips from two consecutive frames.
        struct MetaStrip : public Strip {
            enum : int16_t {
                UNTOUCHED = 0, ///< strip not processed and not part of a connected component
                TOUCHED = 1,   ///< strip not processed but a part of a connected component
                END = -1,      ///< strip is the last in a component
            };

            /// Create a strip that is present only in the newer or the older difference image.
            MetaStrip(const ProtoStrip& strip, bool aNewer)
                : Strip(strip), older(!aNewer), newer(aNewer), motion(0) {}

            /// Create a strip that is present both in the newer and the older difference image.
            MetaStrip(const ProtoStrip& aNewer, const ProtoStrip& aOlder)
                : Strip(Pos16(aNewer.pos.x, (aNewer.pos.y + aOlder.pos.y) / 2),
                        Dims16(aNewer.halfDims.width,
                               (aNewer.halfDims.height + aOlder.halfDims.height) / 2)),
                  older(true),
                  newer(true),
                  motion(aNewer.pos.y - aOlder.pos.y) {}

            // data
            bool older;               ///< strip is present in the older difference image
            bool newer;               ///< strip is present in the newer difference image
            int16_t motion;           ///< change of pos.y between images
            int16_t next = UNTOUCHED; ///< next strip in the connected component/special value
        };

        /// Connected component data.
        struct Component {
            Component(int16_t aFirst) : first(aFirst) {}

            int16_t first; ///< index of the first strip in component
        };

        /// Cluster data.
        struct Cluster {
            /// A cluster's left or right endpoint.
            struct Endpoint {
                int strip; ///< index of the strip at endpoint
                Pos pos;   ///< position of endpoint
            } l, r;

            int numStrips;         ///< total number of strips in cluster
            float approxHeightMin; ///< minimum approximate strip height of components in cluster
            float approxHeightMax; ///< maximum approximate strip height of components in cluster
            float lengthTotal;     ///< approximate length of cluster
            float lengthGaps;      ///< length of all gaps in cluster
            Bounds bounds1;        ///< bounding box around cluster in T and T-1
            Bounds bounds2;        ///< bounding box around cluster in T-1 and T-2

            enum Reason {
                MERGED = -1,
                TOO_FEW_STRIPS = -2,
                TOO_SHORT = -3,
                NOT_AN_OBJECT = -4,
            };

            void setInvalid(Reason reason) { numStrips = int(reason); }
            Reason whyInvalid() const { return Reason(numStrips); }
            bool isInvalid() const { return numStrips < 0; }
        };

        struct MyDetection : public Detection {
            virtual ~MyDetection() override = default;
            MyDetection(const Detection::Object& detObj, const Detection::Predecessor& detPrev,
                        const Cluster* cluster, const ExplorerV3* aMe);
            virtual void getPoints(PointSet& out) const override;

        private:
            const ExplorerV3* const me;
            const Cluster* const mCluster;
        };

        /// Data related to source images.
        struct SourceLevel {
            Format format; ///< source format
            Dims dims;     ///< source dimensions
            Image image1;  ///< newest source image
            Image image2;  ///< source image from previous frame
            Image image3;  ///< source image from two frames before
        };

        /// Data related to decimation levels that will not be processed processed any further.
        /// Serves as a cache during decimation.
        struct IgnoredLevel {
            Image image;
        };

        /// Data related to decimation levels that will be processed. Holds all data required to
        /// detect strips in this frame, as well as some detection results.
        struct ProcessedLevel {
            Image image1;                    ///< newest source image
            Image image2;                    ///< source image from previous frame
            Image image3;                    ///< source image from two frames before
            Image diff1;                     ///< newest difference image
            Image diff2;                     ///< difference image from previous frame
            std::vector<ProtoStrip> strips1; ///< strips in the newest difference image
            std::vector<ProtoStrip> strips2; ///< strips in the difference image from previous frame
            std::vector<MetaStrip> metaStrips; ///< strips created by merging proto-strips
            Image preprocessed;                ///< image ready for strip detection
            int step;                          ///< relative pixel width (due to downscaling)
            int numStrips = 0;                 ///< number of strips detected this frame
        };

        /// Miscellaneous cached objects, typically accessed by a single method.
        struct Cache {
            Image visDiffGray;
            Image visDiffColor;
            Image visColor;
            std::vector<int> halfHeights;
            std::vector<std::pair<float, Cluster*>> sortClusters;
        };

        /// Creates low-resolution versions of the source image using decimation.
        void createLevelPyramid(Image& input);

        /// Applies image-wide operations before strips are detected.
        void preprocess();

        /// Applies image-wide operations before strips are detected.
        void preprocess(ProcessedLevel& level);

        /// Detects strips by iterating over all pixels of the latest difference image.
        void findProtoStrips();

        /// Merges proto-strips from the last two frames.
        void findMetaStrips();

        /// Creates connected components by joining strips together.
        void findComponents();

        /// Creates clusters by joining components together.
        void findClusters();

        /// Locates an object by selecting the best trajectory.
        void findObjects();

        /// Determines whether the given trajectory should be considered a fast-moving object.
        bool isObject(Cluster&) const;

        /// Finds a bounding box enclosing centers of strips which are present in a given difference
        /// image.
        Bounds findClusterBoundsInDiff(const Cluster& cluster, bool newer) const;

        /// Visualizes the results into the visualization image.
        void visualize();

        // data
        SourceLevel mSourceLevel;                 ///< the level with original images
        Subsampler mSubsampler;                     ///< for reducing input image resolution
        mutable Differentiator mDiff;             ///< for creating difference images
        StripGen mStripGen;                       ///< for generating strips
        Agglomerator mAggl;                       ///< for forming clusters from components
        std::vector<IgnoredLevel> mIgnoredLevels; ///< levels that will not be processed
        ProcessedLevel mLevel;                    ///< the level that will be processed
        std::vector<Component> mComponents;       ///< detected components, ordered by x coordinate
        std::vector<Cluster> mClusters;           ///< detected clusters in no particular order
        std::vector<const Cluster*> mObjects;     ///< objects that have been accepted this frame
        int mFrameNum = 0; ///< frame number, 1 when processing the first frame
        Cache mCache;      ///< miscellaneous cached objects
        const Config mCfg; ///< configuration settings
    };
}

#endif // FMO_EXPLORER_IMPL_HPP
